// This file is generated by Codex with some adjustments
// it's just a prototype of MainActor preservation
//
// tests are failing because some overloads are missing
// current assumption (especially given that protocol-based operators in
// other compose files return concrete types (`<name>Func` instead of `some <name>Function`))
// is that MainActor-specific operators should accept non-protocol functions only
// this may help solver, because last attempt to add more overloads here caused a bunch
// of ambiguouty errors in tests 💁

import NominalFunctionTypes
import FunctionCompositionOperators

@inlinable
public func <<< <
	Input,
	Partial,
	Output,
	AFailure: Error,
	BFailure: Error
>(
	_ a: MainActorAsyncThrowingFunc<Partial, Output, AFailure>,
	_ b: MainActorAsyncThrowingFunc<Input, Partial, BFailure>
) -> MainActorAsyncThrowingFunc<Input, Output, Either<BFailure, AFailure>> {
	MainActorAsyncThrowingFunc { (input: Input) async throws(Either<BFailure, AFailure>) -> Output in
		do {
			let partialResult = try await b.run(input)
			do {
				return try await a.run(partialResult)
			} catch {
				throw Either<BFailure, AFailure>.right(error as! AFailure)
			}
		} catch {
			throw Either<BFailure, AFailure>.left(error as! BFailure)
		}
	}
}

@inlinable
public func <<< <
	Input,
	Partial,
	Output,
	Failure: Error
>(
	_ a: MainActorAsyncThrowingFunc<Partial, Output, Failure>,
	_ b: MainActorAsyncThrowingFunc<Input, Partial, Failure>
) -> MainActorAsyncThrowingFunc<Input, Output, Failure> {
	MainActorAsyncThrowingFunc { (input: Input) async throws(Failure) -> Output in
		do {
			let partialResult = try await b.run(input)
			do {
				return try await a.run(partialResult)
			} catch {
				throw error as! Failure
			}
		} catch {
			throw error as! Failure
		}
	}
}

@inlinable
public func <<< <
	Partial,
	Output,
	AFailure: Error,
	B: AsyncThrowingFunction & Sendable
>(
	_ a: MainActorAsyncThrowingFunc<Partial, Output, AFailure>,
	_ b: B
) -> MainActorAsyncThrowingFunc<B.Input, Output, Either<B.Failure, AFailure>>
where B.Output == Partial, Partial: Sendable, B.Input: Sendable {
	MainActorAsyncThrowingFunc { (input: B.Input) async throws(Either<B.Failure, AFailure>) -> Output in
		do {
			let partialResult = try await b.run(input)
			do {
				return try await a.run(partialResult)
			} catch {
				throw Either<B.Failure, AFailure>.right(error as! AFailure)
			}
		} catch {
			throw Either<B.Failure, AFailure>.left(error as! B.Failure)
		}
	}
}

@inlinable
public func <<< <
	Partial,
	Output,
	Failure: Error,
	B: AsyncThrowingFunction & Sendable
>(
	_ a: MainActorAsyncThrowingFunc<Partial, Output, Failure>,
	_ b: B
) -> MainActorAsyncThrowingFunc<B.Input, Output, Failure>
where B.Output == Partial, B.Failure == Failure, Partial: Sendable, B.Input: Sendable {
	MainActorAsyncThrowingFunc { (input: B.Input) async throws(Failure) -> Output in
		do {
			let partialResult = try await b.run(input)
			do {
				return try await a.run(partialResult)
			} catch {
				throw error as! Failure
			}
		} catch {
			throw error as! Failure
		}
	}
}

@inlinable
public func <<< <
	A: AsyncThrowingFunction & Sendable,
	Input,
	Partial,
	BFailure: Error
>(
	_ a: A,
	_ b: MainActorAsyncThrowingFunc<Input, Partial, BFailure>
) -> MainActorAsyncThrowingFunc<Input, A.Output, Either<BFailure, A.Failure>>
where A.Input == Partial, Input: Sendable, Partial: Sendable {
	MainActorAsyncThrowingFunc { (input: Input) async throws(Either<BFailure, A.Failure>) -> A.Output in
		do {
			let partialResult = try await b.run(input)
			do {
				return try await a.run(partialResult)
			} catch {
				throw Either<BFailure, A.Failure>.right(error as! A.Failure)
			}
		} catch {
			throw Either<BFailure, A.Failure>.left(error as! BFailure)
		}
	}
}

@inlinable
public func <<< <
	A: AsyncThrowingFunction & Sendable,
	Input,
	Partial,
	Failure: Error
>(
	_ a: A,
	_ b: MainActorAsyncThrowingFunc<Input, Partial, Failure>
) -> MainActorAsyncThrowingFunc<Input, A.Output, Failure>
where A.Input == Partial, A.Failure == Failure, Input: Sendable, Partial: Sendable {
	MainActorAsyncThrowingFunc { (input: Input) async throws(Failure) -> A.Output in
		do {
			let partialResult = try await b.run(input)
			do {
				return try await a.run(partialResult)
			} catch {
				throw error as! Failure
			}
		} catch {
			throw error as! Failure
		}
	}
}

@inlinable
public func <<< <
	Input,
	Partial,
	Output
>(
	_ a: MainActorAsyncFunc<Partial, Output>,
	_ b: MainActorAsyncFunc<Input, Partial>
) -> MainActorAsyncFunc<Input, Output> {
	MainActorAsyncFunc { (input: Input) async -> Output in
		let partialResult = await b.run(input)
		return await a.run(partialResult)
	}
}

@inlinable
public func <<< <
	Partial,
	Output,
	B: AsyncFunction & Sendable
>(
	_ a: MainActorAsyncFunc<Partial, Output>,
	_ b: B
) -> MainActorAsyncFunc<B.Input, Output>
where B.Output == Partial, Partial: Sendable, B.Input: Sendable {
	MainActorAsyncFunc { (input: B.Input) async -> Output in
		let partialResult = await b.run(input)
		return await a.run(partialResult)
	}
}

@inlinable
public func <<< <
	A: AsyncFunction & Sendable,
	Input,
	Partial
>(
	_ a: A,
	_ b: MainActorAsyncFunc<Input, Partial>
) -> MainActorAsyncFunc<Input, A.Output>
where A.Input == Partial, Input: Sendable, Partial: Sendable {
	MainActorAsyncFunc { (input: Input) async -> A.Output in
		let partialResult = await b.run(input)
		return await a.run(partialResult)
	}
}

@inlinable
public func <<< <
	Input,
	Partial,
	Output,
	AFailure: Error,
	BFailure: Error
>(
	_ a: MainActorSyncThrowingFunc<Partial, Output, AFailure>,
	_ b: MainActorSyncThrowingFunc<Input, Partial, BFailure>
) -> MainActorSyncThrowingFunc<Input, Output, Either<BFailure, AFailure>> {
	MainActorSyncThrowingFunc { (input: Input) throws(Either<BFailure, AFailure>) -> Output in
		do {
			let partialResult = try b.run(input)
			do {
				return try a.run(partialResult)
			} catch {
				throw Either<BFailure, AFailure>.right(error as! AFailure)
			}
		} catch {
			throw Either<BFailure, AFailure>.left(error as! BFailure)
		}
	}
}

@inlinable
public func <<< <
	Input,
	Partial,
	Output,
	Failure: Error
>(
	_ a: MainActorSyncThrowingFunc<Partial, Output, Failure>,
	_ b: MainActorSyncThrowingFunc<Input, Partial, Failure>
) -> MainActorSyncThrowingFunc<Input, Output, Failure> {
	MainActorSyncThrowingFunc { (input: Input) throws(Failure) -> Output in
		do {
			let partialResult = try b.run(input)
			do {
				return try a.run(partialResult)
			} catch {
				throw error as! Failure
			}
		} catch {
			throw error as! Failure
		}
	}
}

@inlinable
public func <<< <
	Partial,
	Output,
	AFailure: Error,
	B: SyncThrowingFunction & Sendable
>(
	_ a: MainActorSyncThrowingFunc<Partial, Output, AFailure>,
	_ b: B
) -> MainActorSyncThrowingFunc<B.Input, Output, Either<B.Failure, AFailure>>
where B.Output == Partial, Partial: Sendable, B.Input: Sendable {
	MainActorSyncThrowingFunc { (input: B.Input) throws(Either<B.Failure, AFailure>) -> Output in
		do {
			let partialResult = try b.run(input)
			do {
				return try a.run(partialResult)
			} catch {
				throw Either<B.Failure, AFailure>.right(error as! AFailure)
			}
		} catch {
			throw Either<B.Failure, AFailure>.left(error as! B.Failure)
		}
	}
}

@inlinable
public func <<< <
	Partial,
	Output,
	Failure: Error,
	B: SyncThrowingFunction & Sendable
>(
	_ a: MainActorSyncThrowingFunc<Partial, Output, Failure>,
	_ b: B
) -> MainActorSyncThrowingFunc<B.Input, Output, Failure>
where B.Output == Partial, B.Failure == Failure, Partial: Sendable, B.Input: Sendable {
	MainActorSyncThrowingFunc { (input: B.Input) throws(Failure) -> Output in
		do {
			let partialResult = try b.run(input)
			do {
				return try a.run(partialResult)
			} catch {
				throw error as! Failure
			}
		} catch {
			throw error as! Failure
		}
	}
}

@inlinable
public func <<< <
	A: SyncThrowingFunction & Sendable,
	Input,
	Partial,
	BFailure: Error
>(
	_ a: A,
	_ b: MainActorSyncThrowingFunc<Input, Partial, BFailure>
) -> MainActorSyncThrowingFunc<Input, A.Output, Either<BFailure, A.Failure>>
where A.Input == Partial, Input: Sendable, Partial: Sendable {
	MainActorSyncThrowingFunc { (input: Input) throws(Either<BFailure, A.Failure>) -> A.Output in
		do {
			let partialResult = try b.run(input)
			do {
				return try a.run(partialResult)
			} catch {
				throw Either<BFailure, A.Failure>.right(error as! A.Failure)
			}
		} catch {
			throw Either<BFailure, A.Failure>.left(error as! BFailure)
		}
	}
}

@inlinable
public func <<< <
	A: SyncThrowingFunction & Sendable,
	Input,
	Partial,
	Failure: Error
>(
	_ a: A,
	_ b: MainActorSyncThrowingFunc<Input, Partial, Failure>
) -> MainActorSyncThrowingFunc<Input, A.Output, Failure>
where A.Input == Partial, A.Failure == Failure, Input: Sendable, Partial: Sendable {
	MainActorSyncThrowingFunc { (input: Input) throws(Failure) -> A.Output in
		do {
			let partialResult = try b.run(input)
			do {
				return try a.run(partialResult)
			} catch {
				throw error as! Failure
			}
		} catch {
			throw error as! Failure
		}
	}
}

@inlinable
public func <<< <
	Input,
	Partial,
	Output
>(
	_ a: MainActorSyncFunc<Partial, Output>,
	_ b: MainActorSyncFunc<Input, Partial>
) -> MainActorSyncFunc<Input, Output> {
	MainActorSyncFunc { (input: Input) -> Output in
		a.run(b.run(input))
	}
}

@inlinable
public func <<< <
	Partial,
	Output,
	B: SyncFunction & Sendable
>(
	_ a: MainActorSyncFunc<Partial, Output>,
	_ b: B
) -> MainActorSyncFunc<B.Input, Output>
where B.Output == Partial, Partial: Sendable, B.Input: Sendable {
	MainActorSyncFunc { (input: B.Input) -> Output in
		a.run(b.run(input))
	}
}

@inlinable
public func <<< <
	A: SyncFunction & Sendable,
	Input,
	Partial
>(
	_ a: A,
	_ b: MainActorSyncFunc<Input, Partial>
) -> MainActorSyncFunc<Input, A.Output>
where A.Input == Partial, Input: Sendable, Partial: Sendable {
	MainActorSyncFunc { (input: Input) -> A.Output in
		a.run(b.run(input))
	}
}
